# Generated by Django 5.2 on 2025-04-24 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_consume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='fat',
            new_name='fats',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='protine',
            new_name='protein',
        ),
    ]
