# Generated by Django 5.2 on 2025-04-24 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_rename_fat_food_fats_rename_protine_food_protein'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='fats',
            new_name='fat',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='protein',
            new_name='protine',
        ),
    ]
